# Generated by Django 2.2.16 on 2022-01-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220120_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='title',
            name='year_gte_2022',
        ),
    ]
