# Generated by Django 2.2.16 on 2022-01-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220120_1511'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='year_gte_2022',
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(check=models.Q(year__gte=1), name='year_gte_1'),
        ),
    ]
