# Generated by Django 2.2.16 on 2022-01-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220120_1633'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='year_gte_1',
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(check=models.Q(year__gte=1000), name='year_gte_1000'),
        ),
    ]
